feeds:
 - feed_id: 'dataflow'
   dataflow_project_id: 'gcp-mindtree-333105'
   dataflow_job_name: 'gcptobqnew'
   dataflow_temp_location: 'gs://mayuri_120199_new/temp/'
   dataflow_staging_location: 'gs://mayuri_120199_new/staging/'
   dataflow_job_region: 'us-east1'
   dataflow_job_publicip_use: 'true'
   dataflow_job_max_worker: '2'
   dataflow_job_worker_machine_type: 'n1-standard-1'
   dataflow_job_subnetwork_enable: 'false'
   dataflow_job_subnetwork_vpc: ''
   dataflow_job_service_account: 'dataflow-temp@gcp-mindtree-333105.iam.gserviceaccount.com'
 
 - feed_id: 'month_melt'
   dataflow_job_reader: 'gcs'
   dataflow_xl_header_row: '9'
   dataflow_job_transform: 'file2tablerow'
   dataflow_job_writer: 'gcs,bq'
   dataflow_job_gcsreadfile: 'gs://mayuri_120199_new/csv/age.*'
   dataflow_csv_has_header: 'true'
   dataflow_csv_delimiter: ','
   dataflow_csv_removequotes: 'true'
   dataflow_xl_melt: 'no'
   dataflow_xl_melt_col : '5:16'
   dataflow_xl_fixed_col: '1:3'
   dataflow_xl_column_row: '3'
   dataflow_xl_header_col: '2:4'
   dataflow_xl_row_num: '4'
   dataflow_xl_sheet_pattern: 'false'
   dataflow_columnmapping: '{"id":"Id","name":"Name","age":"Age","sys_information_dict":"sys_information_dict","source_system_code":"source_system_code","insert_timestamp":"insert_timestamp"}'
   dataflow_source_system_code: 'manual'
   dataflow_job_gcswritefile_path: 'gs://mayuri_120199_new/xlsx_melt/output/success/'
   dataflow_job_gcswritefile_name: 'month_melt_success'
   dataflow_project_id: 'gcp-mindtree-333105'
   dataflow_job_tablename: 'gcp-mindtree-333105:poc.gcspoc_age_success'
   dataflow_job_deadletter_table: 'gcp-mindtree-333105:poc.gcspoc_age_failure'
   dataflow_job_schema_file: 'gs://mayuri_120199_new/config/config_age.json'
   dataflow_job_deadletter_schema_file: 'gs://mayuri_120199_new/config/config_age_failure.json'
   dataflow_job_deadletter_gcswritefile_path: 'gs://mayuri_120199_new/xlsx/output/failure/'
   dataflow_job_deadletter_gcswritefile_name: 'age'
   dataflow_deadletter_columnmapping_mapping: '{"row_number":"row_number","error_type":"error_type","payload":"payload","sys_information_dict":"sys_information_dict","insert_timestamp":"insert_timestamp"}'
  
   


 